# Generated by Django 4.2.7 on 2023-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
